//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratitudeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kirjaus
    {
        public int kirjaus_id { get; set; }
        public string otsake { get; set; }
        public string teksti { get; set; }
        public int kayttaja_id { get; set; }
        public int talo_id { get; set; }
        public System.DateTime pvm { get; set; }
    
        public virtual Kayttajat Kayttajat { get; set; }
        public virtual Talot Talot { get; set; }
    }
}
